### ISSUE TITLE
Documentation incorrect on implementing /api/usersets

### ISSUE THREAD

**Issue by elfuego** [Rijksmuseum/api-issues#1]
The request url right below the heading 'Request' is incorrect is does include 'culture' and should be something like:

https://www.rijksmuseum.nl/api/nl/usersets/123-setname-3?key=fakekey&format=json

**Comment by rasvaan** [comment]
The documentation of usersets is corrected in Rijksmuseum/rijksmuseum.github.io@0a807ec4b3d0cbc85588975ce48b008648dac20a .
