### ISSUE TITLE
Usersets endpoint doesn't work

### ISSUE THREAD

**Issue by JesusM** [Rijksmuseum/api-issues#14]
It seems that the `/usersets` endpoint is not working, as any request to `https://www.rijksmuseum.nl/api/usersets?key=key&format=json` returns a 404 error

**Comment by JesusM** [comment]
My bad, this issue is already covered by https://github.com/Rijksmuseum/api-issues/issues/1, the url needs to contain `culture` information.

**Comment by lukasvan3l** [comment]
You do have a point that it should return a 400 instead of a 404. But good that you got it working!

**Comment by lukasvan3l** [comment]
Hmm I was looking to change this, but on second thought it is appropriately a 404 because the `culture` parameter is in the URL itself, not in the querystring. So will leave it as it is.
