### ISSUE TITLE
Data returned from `https://www.rijksmuseum.nl/api/en/collection?` is partially empty.

### ISSUE THREAD

**Issue by JesusM** [Rijksmuseum/api-issues#17]
Just noticed that the content returned from `https://www.rijksmuseum.nl/api/en/collection?` request doesn't return any image or id, as `webImage` , `headerImage` and `id` properties have `null` data.

Sample:
```
{
  "elapsedMilliseconds": 2040,
  "count": 617010,
  "artObjects": [
    {
      "links": {
        "self": "https://www.rijksmuseum.nl/api/en/collection/SK-A-1365",
        "web": "https://www.rijksmuseum.nl/en/collection/SK-A-1365"
      },
      "id": null,
      "objectNumber": "SK-A-1365",
      "title": "The Battle of Terheide",
      "hasImage": true,
      "principalOrFirstMaker": "",
      "longTitle": null,
      "showImage": false,
      "permitDownload": false,
      "webImage": null,
      "headerImage": null,
      "productionPlaces": []
    },
    {
      "links": {
        "self": "https://www.rijksmuseum.nl/api/en/collection/SK-A-3064",
        "web": "https://www.rijksmuseum.nl/en/collection/SK-A-3064"
      },
      "id": null,
      "objectNumber": "SK-A-3064",
      "title": "Portrait of a Girl Dressed in Blue",
      "hasImage": true,
      "principalOrFirstMaker": "",
      "longTitle": null,
      "showImage": false,
      "permitDownload": false,
      "webImage": null,
      "headerImage": null,
      "productionPlaces": []
    },
   .
   .
   .
  ]
}
```

**Comment by alexolivet** [comment]
Yes, I have noticed the same thing.  The demo page of the rijksmuseum returns no images as well ( at least the first example ).

**Comment by lukasvan3l** [comment]
Hi both, we've done some extensive work on the inner workings of the Rijksmuseum website, specifically its search index. This issue is probably an issue related to that architectural change. I hope to look into why it's behaving this way soon!

**Comment by florestankorp** [comment]
Same here. Please fix this, my app is down too. Everyone using the API is a registered user an email with a heads up would be really nice when you make breaking changes :(

**Comment by JesusM** [comment]
Any update on this? Would be awesome to display content again 😄

**Comment by lukasvan3l** [comment]
It's on our backlog but will take some days to get fixed and rolled out to production.

**Comment by JesusM** [comment]
Any update on this? This endpoint and the search one are still not returning images.

**Comment by JesusM** [comment]
@lukasvan3l I don't want to bother your or the team behind the API, but it'd be nice if this could be fixed? I'm almost sure that most of the services using this API rely on images and collections endpoints and it'd be nice if the start returning images again.

**Comment by JesusM** [comment]
@nicowitteman Yeah as a workaround it could work, but I think you'll agree that this doesn't seem like the best way to fix this. Imagine you have a mobile client using this API endpoint that loads 50 items in a grid at the same time (in a tablet for example), it would require to perform 100 requests to display the images, which IMO it's too much.

**Comment by nicowitteman** [comment]
Of course I agree. It is my experience that many open APIs do not live up to the expectations. In this case, at least there is a workaround. Others just stop without a warning. I do not blame the developers, I think it is the lack of urgency and responsibility felt by the organisations offering the APIs.

**Comment by rasvaan** [comment]
The mapping has been updated and the values should again be available. Let us know if they aren't.
