### ISSUE TITLE
Search results limited to 10K results, makes complete download impossible

### ISSUE THREAD

**Issue by lukasvan3l** [Rijksmuseum/api-issues#18]
Got this one in my inbox:
> I was wondering if the museum would consider providing periodic data dumps on github? The API seems to be stopping at 10k results at the moment. I am currently syncing it as I created my own search index in elasticsearch.

**Comment by nicowitteman** [comment]
I had already submitted that issue in oai-issues last month

**Comment by lukasvan3l** [comment]
Thanks, @nicowitteman

The 10K max is due to memory constraints in our Elasticsearch cluster. For the OAI API we're going to fix this by implementing scrolling with the existing resumptiontoken. 

Unfortunately the JSON API currently doesn't support scrolling through results, and instead accepts a `page` and a `pagesize` parameter. For now I've modified the documentation to reflect this, adding a note at http://rijksmuseum.github.io/#collection and http://rijksmuseum.github.io/#usersets:

> Note that `p * ps` cannot exceed 10.000

In the future we might fix this by editing the JSON API to also work with a resumptiontoken that can scroll through the results, but this will be a breaking change. It is not currently planned.
