### ISSUE TITLE
Documentation - Collection details request example is incorrect

### ISSUE THREAD

**Issue by karengeerts** [Rijksmuseum/api-issues#19]
The documentation uses the following request as an example:

https://www.rijksmuseum.nl/api/nl/collection/sk-c-5?key=fakekey&format=json

When using that url (and replacing the fakekey with a valid key),  a response for an artObject with the value null is generated.

Capitalising the object code in the request url (to SK-C-5) generates the response shown in the documentation.

**Comment by rasvaan** [comment]
Thanks for letting us know, this has been correct Rijksmuseum/rijksmuseum.github.io@72022985a50cbab14b0ea39c2b06ec1038ff19cf
