### ISSUE TITLE
Documentation unclear about set id for /api/usersets

### ISSUE THREAD

**Issue by elfuego** [Rijksmuseum/api-issues#2]
After some trail and error I found that the set key should be made by combining the number appended to your Rijksstudio id and the name of the set you wish to view via the API. For example when you have a Rijksstudio login '12340--janjansen' and a Rijksstudio collection with the name 'Rembrandt'

Your Rijksstudio user id: 12340--janjansen 
Collection you made: Rembrandt

The id of the set/collection in the API will be: 12340- rembrandt
Resulting in an url like for example: https://www.rijksmuseum.nl/api/nl/usersets/12340-rembrandt?key=fake_key&format=json

**Comment by rasvaan** [comment]
Clarified this in Rijksmuseum/rijksmuseum.github.io@e564fc6e9cb61cba3895f69723225eac179474e4
