### ISSUE TITLE
10000 object restriction

### ISSUE THREAD

**Issue by leptdre** [Rijksmuseum/api-issues#20]
I cannot explore more than 10000 asset as the new rule is ps* p cannot exceed 10000. Is there a way to get the available object IDs ??

**Comment by rasvaan** [comment]
For harvests of the full collection data you can use the OAI-PMH API, which has been specifically designed to just that: http://rijksmuseum.github.io/oai
For your specific request you can use the ListIdentifiers verb. We will look into supporting returning more than 1000 object with the website API again in the future.
