### ISSUE TITLE
How can I get page rijksstudio? (Now in Rijksstudio) "https://www.rijksmuseum.nl/api/pages/en/rijksstudio?format=json&key=[myKey]" It doesn't work.

### ISSUE THREAD

**Issue by DinuNuta** [Rijksmuseum/api-issues#23]

**Comment by rasvaan** [comment]
This API endpoint only works for so called 'content pages', so not for the root rijksstudio url.

If you would, for example, like to retrieve the 'content page' about Vermeer, the query below should work:
https://www.rijksmuseum.nl/api/pages/en/rijksstudio/artists/johannes-vermeer?key=[API_KEY]&format=json
