### ISSUE TITLE
How to SET an object in a collection I own

### ISSUE THREAD

**Issue by LejeunePh** [Rijksmuseum/api-issues#24]
All demo's are GET examples.
Can I SET (= INSERT) an object in a collection I own
Can I UPDATE an object in a collection I own
Can I DELETE an object in a collection I own

**Comment by rasvaan** [comment]
Unfortunately, this is not possible. All available options of the API's are listed on http://rijksmuseum.github.io. We might consider adding features where people can add information in the future, but this would entail some significant changes in our infrastructure (e.g. also checking for pushing a lot of information to our servers).
