### ISSUE TITLE
Warn against duplicates in collection

### ISSUE THREAD

**Issue by LejeunePh** [Rijksmuseum/api-issues#25]
Could you warn the user in case of a duplicate entry in a collection. Actually there is no limit to enter the same object multiple times. See https://www.rijksmuseum.nl/nl/rijksstudio/1633433--philippe-lejeune/verzamelingen/testduplicate?ii=0&p=0

**Comment by rasvaan** [comment]
I could imagine some use cases where it would be beneficial to add duplicates. Especially considering the possibility of cropping and highlighting different areas of the image. We might consider adding a warning though.
