### ISSUE TITLE
Paging in collection api incorrect: only multitude of 12 items possible

### ISSUE THREAD

**Issue by elfuego** [Rijksmuseum/api-issues#3]
Weird enough when you specify to receive 10 items you get 12. When you specify 20 items per page you get 24. For example:

https://www.rijksmuseum.nl/api/nl/collection?toppieces=true&imgonly=true&ps=20&p=0&format=jsonp&key=secret_key

This gives you 24 items, although ps=20.

**Comment by rasvaan** [comment]
Can not reproduce this problem anymore. Please reopen an issue when this still is problematic.
