### ISSUE TITLE
imgonly=true is often not true

### ISSUE THREAD

**Issue by elfuego** [Rijksmuseum/api-issues#5]
The parameter 'imgonly=true' should only return art objects that have an image, but that is often not the case. Like for example:

https://www.rijksmuseum.nl/api/nl/collection?imgonly=true&type=glasdia&materiaal=glas&ps=24&p=0&format=jsonp&key=secret_key

The first entry already states "webImage": null, although in this case it has a: 

"headerImage": {
        "guid": "332c1e54-af73-402e-99a3-38acc24efc56",
        "offsetPercentageX": 50,
        "offsetPercentageY": 50,
        "width": 1920,
        "height": 460,
        "url": "http://lh3.ggpht.com/np19pNprIzjxCDU2hCB2zdQHqrTeE6BqzwxvaM5hOdYjyzE29QNqms-UQ5xQ0XZKDDyHmqRsgcSnlkIPY1JTpfbbAUo=s0"
      },

Which is useless for general use. A lot of the images included are headerImages (wide and not high) as used in the design of the Rijksmuseum website, but not the collection images one would expect.
Often headerImages are even not included (sorry, no example here).

**Comment by lizadaly** [comment]
This is still true.

**Comment by rasvaan** [comment]
I checked your example request and all objects now seem to have a webImage. Let us know when this is still a problem somewhere.
