### ISSUE TITLE
[Docs] Collection endpoint parameters meaning is not clear

### ISSUE THREAD

**Issue by paulvi** [Rijksmuseum/api-issues#6]
Hello, thanks you for nice APIs

http://rijksmuseum.github.io/#Collection mentions such parameters as
- `type`    a-z     The type of the art work.

is not clear what is meant.

Also for `maker`, `material` and other how one knows what all possible values are. 

There should be link to list of values for `type`, `maker`, `material` and others.

Possible that would be new endpoint

**Comment by rasvaan** [comment]
We do (not yet) publish data about our structured vocabularies (the type of terms you refer to). This makes it hard to create the API you suggested. In the documentation we refer to the search page, of which you can use the autocompletion functionality to find possible terms. I updated the documentation to refer to the advanced search page, which features autocompletion fields for maker/type/material, I hope that helps Rijksmuseum/rijksmuseum.github.io@9aed1a6f2fcb287510834775d47b8fa76a46cde9
